const brand = {
  primary: '#4A90D9',
  primaryLight: '#E8F0FE',
  primaryDark: '#2D6CB4',
  secondary: '#34C759',
  secondaryLight: '#E8F8EE',
  danger: '#E53935',
  dangerLight: '#FDEDED',
  warning: '#F5A623',
  accent: '#7C6DD8',
  accentLight: '#F0EDFA',
};

export default {
  brand,
  light: {
    text: '#1C1C1E',
    textSecondary: '#6B7280',
    background: '#F8F9FC',
    surface: '#FFFFFF',
    surfaceElevated: '#FFFFFF',
    tint: brand.primary,
    tabIconDefault: '#9CA3AF',
    tabIconSelected: brand.primary,
    border: '#E5E7EB',
    inputBackground: '#F3F4F6',
    userBubble: brand.primary,
    userBubbleText: '#FFFFFF',
    aiBubble: '#F0F2F5',
    aiBubbleText: '#1C1C1E',
    dangerBackground: '#FDEDED',
    headerGradientStart: '#F8F9FC',
    headerGradientEnd: '#EEF1F8',
    cardShadow: 'rgba(0,0,0,0.06)',
  },
  dark: {
    text: '#F1F3F5',
    textSecondary: '#9CA3AF',
    background: '#0F1117',
    surface: '#1A1D27',
    surfaceElevated: '#242836',
    tint: brand.primary,
    tabIconDefault: '#6B7280',
    tabIconSelected: brand.primary,
    border: '#2D3142',
    inputBackground: '#242836',
    userBubble: brand.primary,
    userBubbleText: '#FFFFFF',
    aiBubble: '#1E2233',
    aiBubbleText: '#E5E7EB',
    dangerBackground: '#2D1515',
    headerGradientStart: '#0F1117',
    headerGradientEnd: '#151825',
    cardShadow: 'rgba(0,0,0,0.3)',
  },
};
